### PR TITLE
doc: add deploy on vercel walkthrough

### PR DESCRIPTION
**Pull request by hongchaodeng**

### CODE REVIEW

**Comment by hongchaodeng** [comment]
Please help authorize it. Thanks!
@cbh123 @fofr @zeke @mattt

**Review by zeke — APPROVED** [review]
Fantastic work! This looks great to me.

**Comment by zeke** [comment]
It looks like there's a stray duplicate file here: 

Screenshot 2023-06-13 at 5 15 24 PM

**Comment by hongchaodeng** [comment]
@zeke Nice catch! fixed :)

**Comment by zeke** [comment]
Nice work @hongchaodeng!  🎉 

Thanks for working on this.

**Pull request merged**
