### PR TITLE
Add drag drop to controlnet, and nav update

### PR DESCRIPTION
**Pull request by cbh123**
New in this PR
- drag and drop to controlnet page
- upload controlnet image to supabase
- pill navigation 
- little bug fixes

https://github.com/replicate/zoo/assets/14149230/f7932d64-6a95-4631-a245-802bb0daddae

### CODE REVIEW

**Review by zeke — APPROVED** [review]
In the name of progress, I'd say ship it as is.

Suggestions, none of which are blocking:

- The upload dropzone thing is not really discoverable. It displays briefly then blinks away as the seed example replaces it.
- The dropzone could use a little style love. Maybe just a gray background box with a dotted line border, instead of the clunky blue thing that's there now.
- I wonder if we could call the ControlNet tab something else? Yes, it's ControlNet, but what is the feature more broadly? Text+Image to Image?
- Maybe we should show a blurb about what ControlNet does. Use it a few times and the blurb goes away.

**Comment by cbh123** [comment]
@zeke thanks 😎. I added a quick helper for now. The gray header description (ControlNet models take...) and the "Click to upload your own" will go after first submission. Definitely needs explanation for how ControlNet works, but it's a start


Screenshot 2023-05-30 at 2 58 37 PM

**Comment by cbh123** [comment]
Adding a link to @fofr's video on controlnet pre-processors if you click the header or the "learn more" under models. 

https://www.youtube.com/watch?v=GVCZHCLWON8

Screenshot 2023-05-30 at 3 07 55 PM

Screenshot 2023-05-30 at 3 06 05 PM

**Comment by cbh123** [comment]
Bit nicer uploader too:

Screenshot 2023-05-30 at 3 15 35 PM

**Pull request merged**
